apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: machine-agent-adcapital
  namespace: default
spec:
  selector:
    matchLabels:
      name: machine-agent-adcapital
  template:
    metadata:
      labels:
        name: machine-agent-adcapital
    spec:
      containers:
      - env:
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: mysecret
        - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              key: accountname
              name: mysecret
        - name: APPD_ANALYTICS_MONITOR
          value: "true"
        - name: APPD_DOCKER_VISIBILITY
          value: "true"
        - name: MACHINE_AGENT_PROPERTIES
          value: "-Dappdynamics.sim.enabled=true -Dappdynamics.docker.enabled=true -Dappdynamics.docker.container.containerIdAsHostId.enabled=true"
        image: 975944588697.dkr.ecr.eu-west-2.amazonaws.com/appd-eks-sim-agent:latest
        envFrom:
          - configMapRef:
              name: env-map
        imagePullPolicy: Always
        name: machine-agent-adcapital
        volumeMounts:
        - mountPath: /hostroot
          name: hostroot
          readOnly: false
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - mountPath: /var/lib/docker/containers
          name: docker-containers
        - mountPath: /var/log
          name: docker-logs
        - mountPath: /project
          name: project
        - mountPath: /appdynamics
          name: appdynamics
      restartPolicy: Always
      volumes:
      - name: hostroot
        hostPath:
          path: /
          type: Directory
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: docker-containers
        hostPath:
          path: /var/lib/docker/containers
          type: Directory
      - name: docker-logs
        hostPath:
            path: /var/log
            type: Directory
      - name: project
      - name: appdynamics

---
apiVersion: v1
kind: Service
metadata:
  name: analytics-agent
spec:
  selector:
    name: machine-agent-adcapital
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
status:
  loadBalancer: {}
